### ISSUE TITLE
@ice/pkg-plugin-docusaurus@1.3.0 在纯 react-component 开发模式下不需要 rax-compat

### ISSUE THREAD

**Issue by wssgcg1213** [ice-lab/icepkg#392]
https://github.com/ice-lab/icepkg/blob/main/packages/plugin-docusaurus/src/plugin.js#L5

这里默认去 resolve rax-compat 的路径了, 但是在纯 react 组件开发的场景下是不需要这个包的, 这里需要判断一下

**Comment by wssgcg1213** [comment]
目前现象是构建报错

```text

 WARN  [TRANSFORM-ES2017]  ⚠️ The transformed dist contains @swc/helpers, please make sure @swc/helpers is installed as a dependency.                                                                   21:40:51

ℹ [WATCHER]  COMPILE Watching for changes of paths "/Users/zhuoling/workspace/picture/src"                                                                                                              21:40:51
[ERROR] Error: Cannot find module 'rax-compat'
Require stack:
- /Users/zhuoling/workspace/picture/node_modules/@ice/pkg-plugin-docusaurus/es2017/plugin.js
- /Users/zhuoling/workspace/picture/node_modules/@docusaurus/core/lib/server/plugins/configs.js
- /Users/zhuoling/workspace/picture/node_modules/@docusaurus/core/lib/server/plugins/init.js
- /Users/zhuoling/workspace/picture/node_modules/@docusaurus/core/lib/server/plugins/index.js
- /Users/zhuoling/workspace/picture/node_modules/@docusaurus/core/lib/server/index.js
- /Users/zhuoling/workspace/picture/node_modules/@docusaurus/core/lib/commands/build.js
- /Users/zhuoling/workspace/picture/node_modules/@docusaurus/core/lib/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at Object.<anonymous> (/Users/zhuoling/workspace/picture/node_modules/@ice/pkg-plugin-docusaurus/es2017/plugin.js:4:18)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at module.exports (/Users/zhuoling/workspace/picture/node_modules/import-fresh/index.js:32:59)
    at normalizePluginConfig (/Users/zhuoling/workspace/picture/node_modules/@docusaurus/core/lib/server/plugins/configs.js:20:57)
[INFO] Docusaurus version: 2.1.0

```
